export type PinyinConverter = (text: string) => string;

let loading: Promise<PinyinConverter> | null = null;

/** Tone-marked pinyin with punctuation attached to the preceding syllable. */
export function formatPinyin(raw: string): string {
  return raw.replace(/\s+([，。？！、；：,.!?;:])/g, "$1").trim();
}

/**
 * Loads pinyin-pro on first use only, so the initial app bundle doesn't carry its
 * dictionary. Readings are generated by rules and a dictionary, not a model, and can be
 * wrong for some words (e.g. neutral tones).
 */
export function loadPinyin(): Promise<PinyinConverter> {
  loading ??= import("pinyin-pro")
    .then(
      ({ pinyin }) =>
        (text: string) =>
          formatPinyin(pinyin(text)),
    )
    .catch((error: unknown) => {
      loading = null; // allow a retry
      throw error;
    });
  return loading;
}
